### ISSUE TITLE
There is a problem with Chinese alignment

### ISSUE THREAD

**Issue by bodphi** [prettytable/prettytable#124] opened 2021-08-11 02:22 UTC
```python
tb = pt.PrettyTable()
tb.field_names = ["阶段id", "阶段名称", "结果"]
tb.add_row([1, "阶段1", 1])
tb.add_row([2, "第二个阶段", 2])
tb.add_row([3, "阶段3", 1])
print(tb)
```
![image](https://user-images.githubusercontent.com/29148355/128960066-80f4e5e5-1660-419b-99b2-1b6505ed0490.png)

**Comment by hugovk** [comment] 2021-08-11 06:16
Duplicate of https://github.com/jazzband/prettytable/issues/49, which has a few suggested workarounds.

**Closed as completed by hugovk** 2021-08-11 06:16 UTC
