### ISSUE TITLE
when it contains Chinese, there is no alignment

### ISSUE THREAD

**Issue by liutianping0326** [prettytable/prettytable#94] opened 2021-01-20 06:30 UTC
hi！when it contains Chinese, there is no alignment.

![image](https://user-images.githubusercontent.com/40854706/105136028-ef36cf00-5b2b-11eb-8785-0c1644cd79b9.png)

**Comment by hugovk** [comment] 2021-01-20 07:16
Thank you for the report, this looks like a duplicate of https://github.com/jazzband/prettytable/issues/49.

**Closed as completed by hugovk** 2021-01-20 07:16 UTC
Labels: duplicate
