### ISSUE TITLE
Better display of Chinese

### ISSUE THREAD

**Issue by wuhuanyan** [prettytable/prettytable#49] opened 2020-06-16 09:46 UTC
The display width of one Chinese character is not equal to the display width of two space characters. I recommend using chr (12288) as a filler for Chinese content.

```python
print('[中文]')
print(f"[{chr(12288)}{chr(12288)}]")
print(f"[{' ' * 4}]")
```

```python
[中文]
[　　]
[    ]
```

**Comment by wuhuanyan** [comment] 2020-06-17 01:25
There seems to be no way to achieve it, so I closed it

**Comment by wuhuanyan** [comment] 2020-06-17 03:08
If it is compatible with Chinese, alphanumeric characters need to be converted into full angle characters, and the calculated character length is 1 size. Fill the left and right sides with spaces (or lpad or rpad) with chr(12288). Finally, use "－" as the line divider.
```python
+－－－－－－+－－－－－－－－－－+－－－－－－+－－－－－－+－－－－－－－－－－－－+－－－－－－+－－－－－－－－－+－－－－－－+－－－－－－－－－－－+－－－－－－－－－+－－－－－－－－－+－－－－－－－－－+－－－－+
|　会计月份　|　凭证日期　　　　　|　凭证种类　|　凭证编号　|　会计科目编码　　　　　|　辅助类型　|　辅助编码　　　　|　辅助名称　|　摘要　　　　　　　　|　　　　借方金额　|　　　　贷方金额　|　　　　　　余额　|　方向　|
+－－－－－－+－－－－－－－－－－+－－－－－－+－－－－－－+－－－－－－－－－－－－+－－－－－－+－－－－－－－－－+－－－－－－+－－－－－－－－－－－+－－－－－－－－－+－－－－－－－－－+－－－－－－－－－+－－－－+
|　　　　１　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　期初余额　　　　　　|　　　　　０．０　|　　　　　０．０　|　　　　　　　０　|　平　　|
|　　　　１　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　　　０　|　　　　　　　０　|　　　　　　　０　|　平　　|
|　　　　１　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　　　　　　　０　|　　　　　　　０　|　　　　　　　０　|　平　　|
|　　　　２　|　２０１９０２２８　|　记账　　　|　１１　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　提取备用金　　　　　|　１００００．０　|　　　　　０．０　|　１００００．０　|　借　　|
|　　　　２　|　２０１９０２２８　|　记账　　　|　３５　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　何某某住院慰问金　　|　　　　　０．０　|　　２０００．０　|　　８０００．０　|　借　　|
|　　　　２　|　２０１９０２２８　|　记账　　　|　３５　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　陈某配偶住院慰问金　|　　　　　０．０　|　　２０００．０　|　　６０００．０　|　借　　|
|　　　　２　|　２０１９０２２８　|　记账　　　|　３５　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　林某某住院慰问金　　|　　　　　０．０　|　　２０００．０　|　　４０００．０　|　借　　|
|　　　　２　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　１００００．０　|　　６０００．０　|　　４０００．０　|　借　　|
|　　　　２　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　　６０００．０　|　　４０００．０　|　借　　|
|　　　　３　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　０．０　|　　　　　０．０　|　　４０００．０　|　借　　|
|　　　　３　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　　６０００．０　|　　４０００．０　|　借　　|
|　　　　４　|　２０１９０４３０　|　记账　　　|　５８　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　张某某住院慰问金　　|　　　　　０．０　|　　１５００．０　|　　２５００．０　|　借　　|
|　　　　４　|　２０１９０４３０　|　记账　　　|　５８　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　张某某去世慰问金　　|　　　　　０．０　|　　３０００．０　|　　　５００．０　|　贷　　|
|　　　　４　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　０．０　|　　４５００．０　|　　　５００．０　|　贷　　|
|　　　　４　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　１０５００．０　|　　　５００．０　|　贷　　|
|　　　　５　|　２０１９０５３１　|　记账　　　|　６１　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　老干大学学习费　　　|　　　　　０．０　|　　　１００．０　|　　　６００．０　|　贷　　|
|　　　　５　|　２０１９０５３１　|　记账　　　|　６２　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　临时饭卡充值　　　　|　　　　　０．０　|　　　１００．０　|　　　７００．０　|　贷　　|
|　　　　５　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　０．０　|　　　２００．０　|　　　７００．０　|　贷　　|
|　　　　５　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　１０７００．０　|　　　７００．０　|　贷　　|
|　　　　６　|　２０１９０６３０　|　记账　　　|　４２　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　高某某住院慰问金　　|　　　　　０．０　|　　２０００．０　|　　２７００．０　|　贷　　|
|　　　　６　|　２０１９０６３０　|　记账　　　|　４４　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　何某某住院慰问金　　|　　　　　０．０　|　　２０００．０　|　　４７００．０　|　贷　　|
|　　　　６　|　２０１９０６３０　|　记账　　　|　４５　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　潘某住院慰问金　　　|　　　　　０．０　|　　２０００．０　|　　６７００．０　|　贷　　|
|　　　　６　|　２０１９０６３０　|　记账　　　|　４６　　　|　１００１０１０２０１　|　功能科目　|　２０１３２０１　|　行政运行　|　王某某住院慰问金　　|　　　　　０．０　|　　１５００．０　|　　８２００．０　|　贷　　|
|　　　　６　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　０．０　|　　７５００．０　|　　８２００．０　|　贷　　|
|　　　　６　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　１８２００．０　|　　８２００．０　|　贷　　|
|　　　　７　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　０．０　|　　　　　０．０　|　　８２００．０　|　贷　　|
|　　　　７　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　１８２００．０　|　　８２００．０　|　贷　　|
|　　　　８　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本月合计　　　　　　|　　　　　０．０　|　　　　　０．０　|　　８２００．０　|　贷　　|
|　　　　８　|　　　　　　　　　　|　　　　　　|　　　　　　|　　　　　　　　　　　　|　　　　　　|　　　　　　　　　|　　　　　　|　本年累计　　　　　　|　１００００．０　|　１８２００．０　|　　８２００．０　|　贷　　|
+－－－－－－+－－－－－－－－－－+－－－－－－+－－－－－－+－－－－－－－－－－－－+－－－－－－+－－－－－－－－－+－－－－－－+－－－－－－－－－－－+－－－－－－－－－+－－－－－－－－－+－－－－－－－－－+－－－－+
```

**Comment by hugovk** [comment] 2020-10-04 11:24
Please could you provide a minimal code snippet including PrettyTable that reproduces it?

Does it happen with latest `master`? It sounds like https://github.com/jazzband/prettytable/pull/56 may have helped.

**Comment by hugovk** [comment] 2020-10-04 19:53
`master` has just been released as 1.0.0, please can you re-test with that?

https://pypi.org/project/prettytable/1.0.0/

**Comment by wuhuanyan** [comment] 2020-10-09 09:44
> `master` has just been released as 1.0.0, please can you re-test with that?
> 
> https://pypi.org/project/prettytable/1.0.0/

```python
from prettytable import PrettyTable

x = PrettyTable()
x.field_names = ["城市名称", "城市名称编码", "人员", "人均工资(元)"]
x.add_row(["广州", 1295, 1158259, 600.5])
x.add_row(["石家庄", 5905, 1857594, 1146.4])
x.add_row(["加利福利亚", 112, 120900, 1714.7])
x.add_row(["呼和浩特", 1357, 205556, 619.5])

print(x)
```

 released as 1.0.0
```
+------------+--------------+---------+--------------+
|  城市名称  | 城市名称编码 |   人员  | 人均工资(元) |
+------------+--------------+---------+--------------+
|    广州    |     1295     | 1158259 |    600.5     |
|   石家庄   |     5905     | 1857594 |    1146.4    |
| 加利福利亚 |     112      |  120900 |    1714.7    |
|  呼和浩特  |     1357     |  205556 |    619.5     |
+------------+--------------+---------+--------------+
```

**Comment by hugovk** [comment] 2020-10-09 10:01
I get the same (with both PrettyTable 0.7.2 and 1.0.0), it looks good for me in the terminal (iTerm2):

![image](https://user-images.githubusercontent.com/1324225/95569806-bec09e80-0a2e-11eb-895b-87d2b253e266.png)

But not in GitHub monospace:

```
+------------+--------------+---------+--------------+
|  城市名称  | 城市名称编码 |   人员  | 人均工资(元) |
+------------+--------------+---------+--------------+
|    广州    |     1295     | 1158259 |    600.5     |
|   石家庄   |     5905     | 1857594 |    1146.4    |
| 加利福利亚 |     112      |  120900 |    1714.7    |
|  呼和浩特  |     1357     |  205556 |    619.5     |
+------------+--------------+---------+--------------+
```

**Comment by wuhuanyan** [comment] 2020-10-09 10:25
Thank you for your quick reply.
I tested the output of the command window in Python 3.6.8, pretty table 1.0.0 environment, which is a perfect display format.
So the problem is that it appears in the "pycharm" run window.

In addition, I noticed that every Chinese character in the command window has extra display width, but not under "pycharm", which should be the cause of the problem.

![1602238922258](https://user-images.githubusercontent.com/39271126/95572501-a0719780-0a5c-11eb-8d83-4ad5b840130d.jpg)

**Comment by hugovk** [comment] 2020-10-09 10:41
Hmm, my PyCharm looks okay.

I added some extra debug:

```python
import os
import sys
import prettytable
print(sys.version)
print(prettytable.__version__)
print(os.environ["TERM"])
```

# iTerm2

![image](https://user-images.githubusercontent.com/1324225/95574072-1235eb00-0a35-11eb-8098-aee01bd9bb97.png)

# PyCharm

![image](https://user-images.githubusercontent.com/1324225/95574025-034f3880-0a35-11eb-90ac-f089d4ba99b2.png)

**Comment by wuhuanyan** [comment] 2020-10-10 02:51
# command window
![image](https://user-images.githubusercontent.com/39271126/95643972-9f387d00-0ae5-11eb-8f6a-4439b6a32355.png)

# PyCharm
![image](https://user-images.githubusercontent.com/39271126/95644029-05bd9b00-0ae6-11eb-81f1-ad6964a723f2.png)

```python
vi ~/.bash_profile
export TERM="xterm-256color"
source ~/.bash_profile
```
![image](https://user-images.githubusercontent.com/39271126/95644080-7b296b80-0ae6-11eb-8177-17d671cacda4.png)

**Comment by hugovk** [comment] 2020-10-10 05:09
@vrza Hi! Do you by any chance know what's up here?

**Comment by wuhuanyan** [comment] 2020-10-10 06:43
I think my pycharm settings are different from yours.
Can I see your settings?
pycharm->preferences->Editor->Color Scheme->Console Font

**Comment by hugovk** [comment] 2020-10-10 11:59
I have JetBrains Mono:

![image](https://user-images.githubusercontent.com/1324225/95654524-29dea380-0b09-11eb-9387-12b10ecaec0e.png)

**Comment by vrza** [comment] 2020-10-13 10:20
Seems to work fine for me with JetBrains Mono in PyCharm on Linux

![pycharm-jetbrains-mono](https://user-images.githubusercontent.com/1699472/95848557-7d8dfe80-0d4e-11eb-8469-09a9886cc0f0.png)

**Comment by vrza** [comment] 2020-10-13 10:30
In some other applications, like Gedit, Kate and Slack on Linux (pictured below), however, it is problematic.

![slack-prettytable](https://user-images.githubusercontent.com/1699472/95849276-89c68b80-0d4f-11eb-919c-cdb077fa873c.png)

Chinese characters that should be rendered to be exactly 2 "cells" wide (where cell is the width of a single monospace font character) are rendered with width < 2.

Vim, Emacs and most terminal emulators seem to render it nicely.

On first glance, the issue seems to be in the application that's rendering the text or the rendering engine it uses.

This is _not_ a bug in prettytable or the [wcwidth](https://github.com/jquast/wcwidth) library. In the terminal we can only work with whole cells, and we rely on the application (e.g. terminal emulator) to align all characters to integer multiples of 1 cell.

**Comment by vrza** [comment] 2020-10-13 14:26
It seems like quite a complex issue as some character widths when printed in monospaced font are not standardized. This blog post may have some useful information (do notice how many times it was edited): https://denisbider.blogspot.com/2015/09/when-monospace-fonts-arent-unicode.html

**Comment by onion1003** [comment] 2021-03-31 07:20
![solution](https://user-images.githubusercontent.com/17641342/113105672-6d9ea400-9234-11eb-9278-a1699b15e967.png)
choose “Emulate terminal in output console” in pycharm will solve the display problem in pycharm.

For pandas, you also need to add
```python
pd.set_option('display.unicode.ambiguous_as_wide', True)
pd.set_option('display.unicode.east_asian_width', True)
```

**Comment by swfcsh** [comment] 2021-06-11 07:08
> ![solution](https://user-images.githubusercontent.com/17641342/113105672-6d9ea400-9234-11eb-9278-a1699b15e967.png)
> choose “Emulate terminal in output console” in pycharm will solve the display problem in pycharm.
> 
> For pandas, you also need to add
> 
> ```python
> pd.set_option('display.unicode.ambiguous_as_wide', True)
> pd.set_option('display.unicode.east_asian_width', True)
> ```

It works fine for me! 
Thanks!

**Closed as completed** 2021-12-22 09:01 UTC
